name:                brave-pose-gui
version:             0.1.0.0
github:              "githubuser/brave-pose-gui"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/brave-pose-gui#readme>

dependencies:
- base >= 4.12.0.0 && < 5
- GLFW-b
- OpenGLRaw
- OpenGL
- vector
- mtl
- lens
- containers
- linear
- stm
- transformers
- bytestring
- unordered-containers
- HUnit
- directory
- time
- uuid

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  brave-pose-gui-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brave-pose-gui

tests:
  brave-pose-gui-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brave-pose-gui
